# Generated by Django 4.1.7 on 2023-03-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redBelt', '0004_rename_text_quote_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='user',
            new_name='addby',
        ),
        migrations.AddField(
            model_name='quote',
            name='favourite',
            field=models.ManyToManyField(related_name='favor', to='redBelt.user'),
        ),
    ]
