# Generated by Django 4.1.7 on 2023-03-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheUsers', '0002_profile_post_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
