# Generated by Django 4.1.7 on 2023-02-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wall', '0002_rename_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=254, unique=True), max_length=100),
        ),
    ]
